spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/servlettest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
